services:
  backend:
    image: jjpisano05/group05backend:1.4
    container_name: group05backend
    ports:
      - '22131:22131'
    expose:
      - '22131'
    networks:
      - group05network
    environment:
      - HF_TOKEN=()
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:22131/']
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  frontend:
    image: jjpisano05/group05frontend:1.2
    container_name: group05frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - '22130:22130'
    expose:
      - '22130'
    environment:
      - HF_TOKEN=()
    networks:
      - group05network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '22132:9090'
    depends_on:
      - frontend
      - backend
    networks:
      - group05network

networks:
  group05network:
    driver: bridge

volumes:
  prometheus_data:
    driver: local
